# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_iu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 772)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(0, 390, 791, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tabMenu = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMenu.setEnabled(True)
        self.tabMenu.setGeometry(QtCore.QRect(40, 40, 751, 291))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabMenu.setFont(font)
        self.tabMenu.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabMenu.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabMenu.setAccessibleName("")
        self.tabMenu.setAutoFillBackground(True)
        self.tabMenu.setObjectName("tabMenu")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setEnabled(True)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 224))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lNC = QtWidgets.QLabel(self.formLayoutWidget)
        self.lNC.setEnabled(True)
        self.lNC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lNC.setObjectName("lNC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lNC)
        self.Nc = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.Nc.setEnabled(True)
        self.Nc.setAcceptDrops(False)
        self.Nc.setMaximum(1000)
        self.Nc.setObjectName("Nc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Nc)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Nll = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.Nll.setEnabled(True)
        self.Nll.setMaximum(1000)
        self.Nll.setObjectName("Nll")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Nll)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.Tpll = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.Tpll.setEnabled(True)
        self.Tpll.setObjectName("Tpll")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Tpll)
        self.tabMenu.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.MOS = QtWidgets.QComboBox(self.tab_2)
        self.MOS.setGeometry(QtCore.QRect(100, 40, 341, 31))
        self.MOS.setMinimumContentsLength(0)
        self.MOS.setObjectName("MOS")
        self.MOS.addItem("")
        self.MOS.addItem("")
        self.MOS.addItem("")
        self.MOS.addItem("")
        self.MOS.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(50, 45, 51, 21))
        self.label_5.setObjectName("label_5")
        self.tabMenu.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 741, 221))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 5, 0, 5)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.Rt = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.Rt.setEditable(False)
        self.Rt.setObjectName("Rt")
        self.Rt.addItem("")
        self.Rt.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Rt)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.Rr = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_2)
        self.Rr.setDecimals(1)
        self.Rr.setMaximum(1000.0)
        self.Rr.setSingleStep(0.1)
        self.Rr.setObjectName("Rr")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Rr)
        self.encapsulacionLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.encapsulacionLabel.setObjectName("encapsulacionLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.encapsulacionLabel)
        self.TcWan = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.TcWan.setEditable(False)
        self.TcWan.setObjectName("TcWan")
        self.TcWan.addItem("")
        self.TcWan.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.TcWan)
        self.tabMenu.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 78, 22))
        self.label_11.setObjectName("label_11")
        self.ETH = QtWidgets.QComboBox(self.tab_4)
        self.ETH.setEnabled(True)
        self.ETH.setGeometry(QtCore.QRect(80, 10, 646, 22))
        self.ETH.setEditable(False)
        self.ETH.setObjectName("ETH")
        self.ETH.addItem("")
        self.ETH.addItem("")
        self.ETH.addItem("")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 78, 22))
        self.label_12.setObjectName("label_12")
        self.ENC = QtWidgets.QComboBox(self.tab_4)
        self.ENC.setGeometry(QtCore.QRect(80, 110, 646, 22))
        self.ENC.setEditable(False)
        self.ENC.setObjectName("ENC")
        self.ENC.addItem("")
        self.ENC.addItem("")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 210, 78, 22))
        self.label_13.setObjectName("label_13")
        self.TUN = QtWidgets.QComboBox(self.tab_4)
        self.TUN.setGeometry(QtCore.QRect(80, 210, 646, 22))
        self.TUN.setEditable(False)
        self.TUN.setObjectName("TUN")
        self.TUN.addItem("")
        self.TUN.addItem("")
        self.TUN.addItem("")
        self.tabMenu.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_5)
        self.formLayoutWidget_3.setEnabled(True)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 691, 224))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setEnabled(True)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.Pb = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.Pb.setMaximum(1.0)
        self.Pb.setSingleStep(0.01)
        self.Pb.setObjectName("Pb")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Pb)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setEnabled(True)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.BWres = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_3)
        self.BWres.setEnabled(True)
        self.BWres.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.BWres.setMaximum(1.0)
        self.BWres.setSingleStep(0.01)
        self.BWres.setObjectName("BWres")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.BWres)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ruta = QtWidgets.QFontComboBox(self.formLayoutWidget_3)
        self.ruta.setObjectName("ruta")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ruta)
        self.tabMenu.addTab(self.tab_5, "")
        self.pbCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.pbCalcular.setEnabled(True)
        self.pbCalcular.setGeometry(QtCore.QRect(300, 450, 211, 41))
        self.pbCalcular.setObjectName("pbCalcular")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMenu.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lNC.setText(_translate("MainWindow", "Número de clientes:"))
        self.label.setText(_translate("MainWindow", "Número de llamadas"))
        self.label_2.setText(_translate("MainWindow", "Tiempo medio de llamada"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab), _translate("MainWindow", "Llamadas"))
        self.MOS.setItemText(0, _translate("MainWindow", "Excelente"))
        self.MOS.setItemText(1, _translate("MainWindow", "Buena"))
        self.MOS.setItemText(2, _translate("MainWindow", "Aceptable"))
        self.MOS.setItemText(3, _translate("MainWindow", "Pobre"))
        self.MOS.setItemText(4, _translate("MainWindow", "Mala"))
        self.label_5.setText(_translate("MainWindow", "MOS"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_2), _translate("MainWindow", "QoE"))
        self.label_7.setText(_translate("MainWindow", "Retardo total "))
        self.Rt.setItemText(0, _translate("MainWindow", "Aceptable"))
        self.Rt.setItemText(1, _translate("MainWindow", "Moderadamente aceptable"))
        self.label_8.setText(_translate("MainWindow", "Retardo de red"))
        self.encapsulacionLabel.setText(_translate("MainWindow", "TcWan"))
        self.TcWan.setItemText(0, _translate("MainWindow", "RTP"))
        self.TcWan.setItemText(1, _translate("MainWindow", "cRTP"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_3), _translate("MainWindow", "QoS"))
        self.label_11.setText(_translate("MainWindow", "ETHERNET"))
        self.ETH.setItemText(0, _translate("MainWindow", "ETHERNET"))
        self.ETH.setItemText(1, _translate("MainWindow", "ETHERNET8021Q"))
        self.ETH.setItemText(2, _translate("MainWindow", "ETHERNETQinQ"))
        self.label_12.setText(_translate("MainWindow", "ENLACE"))
        self.ENC.setItemText(0, _translate("MainWindow", "PPP"))
        self.ENC.setItemText(1, _translate("MainWindow", "PPOE"))
        self.label_13.setText(_translate("MainWindow", "TÚNELES"))
        self.TUN.setItemText(0, _translate("MainWindow", "IPSEC"))
        self.TUN.setItemText(1, _translate("MainWindow", "L2TP"))
        self.TUN.setItemText(2, _translate("MainWindow", "MPLS"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_4), _translate("MainWindow", "GoS"))
        self.label_15.setText(_translate("MainWindow", "Probabilidad de bloqueo"))
        self.label_16.setText(_translate("MainWindow", "Ancho de banda (BWres)"))
        self.label_3.setText(_translate("MainWindow", "Ruta del fichero"))
        self.ruta.setCurrentText(_translate("MainWindow", "C:/"))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_5), _translate("MainWindow", "Ancho de banda"))
        self.pbCalcular.setText(_translate("MainWindow", "Siguiente paso"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

