# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_iu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 772)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(0, 530, 791, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gbTopologia = QtWidgets.QGroupBox(self.centralwidget)
        self.gbTopologia.setEnabled(True)
        self.gbTopologia.setGeometry(QtCore.QRect(10, 290, 751, 171))
        self.gbTopologia.setObjectName("gbTopologia")
        self.iCodecs = QtWidgets.QComboBox(self.gbTopologia)
        self.iCodecs.setEnabled(True)
        self.iCodecs.setGeometry(QtCore.QRect(280, 10, 171, 22))
        self.iCodecs.setObjectName("iCodecs")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.iCodecs.addItem("")
        self.casdaed = QtWidgets.QTabWidget(self.centralwidget)
        self.casdaed.setEnabled(True)
        self.casdaed.setGeometry(QtCore.QRect(10, 40, 751, 231))
        self.casdaed.setObjectName("casdaed")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setEnabled(True)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lNC = QtWidgets.QLabel(self.formLayoutWidget)
        self.lNC.setEnabled(True)
        self.lNC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lNC.setObjectName("lNC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lNC)
        self.iNC = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.iNC.setEnabled(True)
        self.iNC.setObjectName("iNC")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iNC)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setEnabled(True)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.iNC_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.iNC_2.setEnabled(True)
        self.iNC_2.setObjectName("iNC_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.iNC_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox_2.setEnabled(True)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.casdaed.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 40, 341, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 55, 16))
        self.label_5.setObjectName("label_5")
        self.casdaed.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 741, 204))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 5, 0, 5)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.casdaed.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.casdaed.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.casdaed.addTab(self.tab_5, "")
        self.pbCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.pbCalcular.setEnabled(True)
        self.pbCalcular.setGeometry(QtCore.QRect(30, 630, 211, 41))
        self.pbCalcular.setObjectName("pbCalcular")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(420, 620, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(110, 460, 70, 17))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.casdaed.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbTopologia.setTitle(_translate("MainWindow", "Topología"))
        self.iCodecs.setItemText(0, _translate("MainWindow", "G711"))
        self.iCodecs.setItemText(1, _translate("MainWindow", "G729"))
        self.iCodecs.setItemText(2, _translate("MainWindow", "G723.1(6.3)"))
        self.iCodecs.setItemText(3, _translate("MainWindow", "G723.1(5.3)"))
        self.iCodecs.setItemText(4, _translate("MainWindow", "G726(32)"))
        self.iCodecs.setItemText(5, _translate("MainWindow", "G728"))
        self.iCodecs.setItemText(6, _translate("MainWindow", "G722_64k"))
        self.lNC.setText(_translate("MainWindow", "Número de clientes:"))
        self.label.setText(_translate("MainWindow", "Número de llamadas"))
        self.label_2.setText(_translate("MainWindow", "Tiempo medio de llamada"))
        self.label_3.setText(_translate("MainWindow", "Probabilidad de llamada"))
        self.label_4.setText(_translate("MainWindow", "Ancho de banda (BWres)"))
        self.label_6.setText(_translate("MainWindow", "Encapsulación"))
        self.casdaed.setTabText(self.casdaed.indexOf(self.tab), _translate("MainWindow", "Llamadas"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Excelente"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Buena"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Aceptable"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Pobre"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Mala"))
        self.label_5.setText(_translate("MainWindow", "MOS"))
        self.casdaed.setTabText(self.casdaed.indexOf(self.tab_2), _translate("MainWindow", "QoE"))
        self.label_7.setText(_translate("MainWindow", "Retardo total "))
        self.label_8.setText(_translate("MainWindow", "Retardo de red"))
        self.label_9.setText(_translate("MainWindow", "Jitter total"))
        self.checkBox_3.setText(_translate("MainWindow", "cRTP"))
        self.checkBox_2.setText(_translate("MainWindow", "RTP"))
        self.casdaed.setTabText(self.casdaed.indexOf(self.tab_3), _translate("MainWindow", "QoS"))
        self.casdaed.setTabText(self.casdaed.indexOf(self.tab_4), _translate("MainWindow", "GoS"))
        self.casdaed.setTabText(self.casdaed.indexOf(self.tab_5), _translate("MainWindow", "Ancho de banda"))
        self.pbCalcular.setText(_translate("MainWindow", "Calcular"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

