# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_iu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaWindow(object):
    def setupUi(self, VentanaWindow):
        VentanaWindow.setObjectName("VentanaWindow")
        VentanaWindow.resize(1028, 573)
        font = QtGui.QFont()
        font.setPointSize(13)
        VentanaWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(VentanaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.pbCalcular.setGeometry(QtCore.QRect(330, 390, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pbCalcular.setFont(font)
        self.pbCalcular.setObjectName("pbCalcular")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.validCodecs = QtWidgets.QLCDNumber(self.centralwidget)
        self.validCodecs.setGeometry(QtCore.QRect(440, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.validCodecs.setFont(font)
        self.validCodecs.setLineWidth(1)
        self.validCodecs.setProperty("intValue", 0)
        self.validCodecs.setObjectName("validCodecs")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 1011, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(11)
        self.sendMail = QtWidgets.QPushButton(self.centralwidget)
        self.sendMail.setGeometry(QtCore.QRect(330, 450, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sendMail.setFont(font)
        self.sendMail.setObjectName("sendMail")
        self.correo = QtWidgets.QLineEdit(self.centralwidget)
        self.correo.setEnabled(True)
        self.correo.setGeometry(QtCore.QRect(510, 460, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.correo.setFont(font)
        self.correo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.correo.setObjectName("correo")
        self.correoEnviado = QtWidgets.QLabel(self.centralwidget)
        self.correoEnviado.setEnabled(False)
        self.correoEnviado.setGeometry(QtCore.QRect(770, 460, 21, 16))
        self.correoEnviado.setObjectName("correoEnviado")
        VentanaWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VentanaWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 24))
        self.menubar.setObjectName("menubar")
        VentanaWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VentanaWindow)
        self.statusbar.setObjectName("statusbar")
        VentanaWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaWindow)
        QtCore.QMetaObject.connectSlotsByName(VentanaWindow)

    def retranslateUi(self, VentanaWindow):
        _translate = QtCore.QCoreApplication.translate
        VentanaWindow.setWindowTitle(_translate("VentanaWindow", "MainWindow"))
        self.pbCalcular.setText(_translate("VentanaWindow", "Modificar parámetros previos"))
        self.label.setText(_translate("VentanaWindow", "CODECS VALIDOS ENCONTRADOS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("VentanaWindow", "CODEC"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("VentanaWindow", "MOS"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("VentanaWindow", "RT"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("VentanaWindow", "BHT"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("VentanaWindow", "Nll"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("VentanaWindow", "BWll"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("VentanaWindow", "BWst"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("VentanaWindow", "PaquetesRTP"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("VentanaWindow", "Pperd"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("VentanaWindow", "E[Rafaga]"))
        self.sendMail.setText(_translate("VentanaWindow", "SEND MAIL"))
        self.correo.setText(_translate("VentanaWindow", "ejemplo@correo.ugr.es"))
        self.correoEnviado.setText(_translate("VentanaWindow", "✅"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaWindow = QtWidgets.QMainWindow()
    ui = Ui_VentanaWindow()
    ui.setupUi(VentanaWindow)
    VentanaWindow.show()
    sys.exit(app.exec_())

